maps/tag_death_machina.res
maps/tag_death_machina.txt

gfx/env/simplenightbk.tga
gfx/env/simplenightdn.tga
gfx/env/simplenightft.tga
gfx/env/simplenightlf.tga
gfx/env/simplenightrt.tga
gfx/env/simplenightup.tga
sound/mistax88/arenaonlyone.wav
sound/mistax88/bigthud.wav
sound/mistax88/boogoround.wav
sound/mistax88/computerloop1.wav
sound/mistax88/computerloop2.wav
sound/mistax88/doomdoor1.wav
sound/mistax88/doomdoor2.wav
sound/mistax88/doomdoor3.wav
sound/mistax88/holdyaears.wav
sound/mistax88/lowpolydesire.wav
sound/mistax88/supermodloop.wav
sound/mistax88/theyfloat.wav
sound/mistax88/trap.wav
sound/mistax88/urbannightloop1.wav
sound/mistax88/zeldaitemget.wav